"""Evidence-first, dependency-aware medical-agent MVP.

This package intentionally uses only the Python standard library so that the
demo can run in a restricted local environment.  Its model-facing contracts
are deliberately small; provenance and audit fields are generated by code.
"""

from .service import MedicalAgentService

__all__ = ["MedicalAgentService"]
